Economy:
  Database:
    # Type of database used, MySQL, SQLite and others will be added soon.
    # Available types: H2
    type: H2
    # You can change this value to 0 if you want to make server more difficult
    defaultMoney: 1000
    # You can remove it if you want, and you can use it in messages using: "%currency%"
    currency: '$'

  # Not used for now
  TransactionUtils:
    # %money_giver_name%, %money_amount%
    getMoneyMessage: "%money_giver_name% gave you %money_amount%%currency%!"
    notEnoughMoney: "&cYou don't have enough money!"
    receiverDoesntExists: "&cReceiver doesn't exists!"

  MoneyExecutor:
    # %money_target_name%, %money_target_amount%
    dontHavePermission: "&cYou don't have permission to use this command!"
    moneyMessage: "&f&l%money_target_name% &7has &f&l%money_target_amount%%currency%&7!"
    yourselfMoneyMessage: "&7You have &f&l%money_target_amount%%currency%&7!"
    lastArgumentNotNumber: "&cLast argument isn't a valid number!"
    successfulAction: "&7That action was successful done!"
    badUsage: "&7Use: &f&l/money [PLAYER] [ACTION] [AMOUNT]!"
    targetDontExists: "&cTarget doesn't exists!"

  PayExecutor:
    dontHavePermission: "&cYou don't have permission to use this command."
    badUsage: "&7Use: &f&l/pay {PLAYER} {AMOUNT}!"
    cantPayYourself: "&cYou can't pay to yourself!"
    lastArgumentNotNumber: "&cLast argument isn't a valid number!"
    dontHaveEnoughMoney: "&cYou don't have enough money!"
    notAvailableToConsole: "&fThis command is unavailable to a Console."
    targetDoesntExists: "&cTarget doesn't exists!"
    receivedMoney: "&f&l%money_sender_name% &7send you &f&l%money_sent_amount%%currency%&7!"
    gaveMoney: "&7You have send &f&l%money_receiver_name% %money_sent_amount%%currency%&7!"

Reload:
  dontHavePermission: "&cYou don't have permission to use this command."
  successAction: "&7OpEconomy reloaded!"

BalanceTop:
  # This number represents how many players would show in one page
  pageSize: 10
  pageFront: "&fDownloading money of &7%all_players%&f players, please wait. \n&7Richest players: &7(%current_date%) \n&e--- &6Balance Top &e- &6Page %current_page% &e---\n"
  pageMiddle: "%player_number% %player_nick%, %player_money%%currency%\n"
  pageEnd:
    # This function adds ability to click on a text which moves you to previous / next page
    enabled: true
    nextPage: "&7[&f&lNext Page&7] "
    previousPage: "&7[&f&lPrevious Page&7] "
    # HoverMessage will show when cursor is in text area
    hoverMessage: "Click to go to the page!"
  Executor:
    dontHavePermission: "&cYou don't have permission to use this command."
    badUsage: "&7Use: &f&l/baltop {PAGE}!"
    lastArgumentNotNumber: "&cLast argument isn't a valid number!"

Redeem:
  # Too small code can be easy to guess (Best: 10, Minimum: 1 (to even use codes), Recommended: 8 or 6)
  codeLength: 8
  # If this is enabled, it will remove additional code if it's too big or add to fill length requirement
  # Preferred to be enabled (true)
  removeAdditional: true
  dontHavePermission: "&cYou don't have permission to use this command."
  notAvailableToConsole: "&fThis command is unavailable to a Console."
  validCodeEntered: "&7Your entered code is valid! Reward: &f&l%redeem_reward%&7!"
  notValidCodeEntered: "&7Your entered code is invalid / expired."
  lastArgumentNotNumber: "&cLast argument isn't a valid number!"
  createdCode: "&7Created code: &f&l%redeem_code_name%&7!"
  badUsage: "&7Use: &f&l/redeem &f&l{CODE / CREATE / REMOVE / INFO} [- / (Random or Code) / Code] [(Only Create) Max Uses] [(Only Create) Reward]!"
  removedCode: "&7Code has been removed."
  infoMessage: "&7Code: &f&l%redeem_code_name% \n&7Reward: &f&l%redeem_reward% \n&7Max Uses: &f&l%redeem_maxUses% \n&7Uses: &f&l%redeem_uses% \n&7Players: &f&l%redeem_players_name%"

DeathSettings:
  # IF YOU DON'T WANT TO HAVE ANY OF THESE SETTINGS SET THEM TO 0
  # You can't have lostPercentageOfMoneyOnDeath turned on in this case or plugin will break
  # Lost specific amount of money on death
  # Change to 0 if you want to disable
  lostMoneyOnDeath: 100.0
  # You can't have lostMoneyOnDeath turned on in this case or plugin will break
  # Lost specific percentage of money on death
  # Change to 0 if you want to disable
  lostPercentageOfMoneyOnDeath: 0.01
  # Select 'true' if you want to killer getting money from killed player (recommended for RP servers)
  # Select 'false' if you want to disable
  killerGetsMoney: true

Notes:
  enabled: true
  notesItem:
    name: "&7MoneyNote &8(Right Click)"
    lore:
      - '&7Note of value %note_value%%opeconomy_currency%'
      - '&7Signed by &7Imperial Bank of Server'
    material: Paper
    # If Enchanted is enabled, it will make item 'glow'
    enchanted: true
    # If Hidden is enabled, it will hide all item's attributes
    hidden: true
  sounds:
    # List of sounds available is here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
    withdrawSound: 'ENTITY_COW_HURT'
    depositSound: 'BLOCK_ANVIL_FALL'
  notesSettings:
    minimumNote: 5.0
    maximumNote: 50000.0
  messages:
    dontHavePermission: "&cYou don't have permission to use this command."
    lastArgumentNotNumber: "&cLast argument isn't a valid number!"
    notAvailableToConsole: "&fThis command is unavailable to a Console."
    badUsage: "&7Use: &f&l/withdraw {AMOUNT}!"
    withdrawnMoney: "&c- %money_withdrawn%%opeconomy_currency%"
    depositedMoney: "&a+ %money_deposited%%opeconomy_currency%"
    tooBigOrSmallAmount: "&cYou can withdraw from 5%opeconomy_currency% up to 50000%opeconomy_currency%.\nYou can't withdraw %tried_withdraw_amount%%opeconomy_currency%!"

TimeEqualsMoney:
  # This allows you to reward yours players that they are spending time on your server
  enabled: true
  reward:
    # Integer every is telling loop for how long one loop should have been
    every: 60 # In seconds
    # Integer length is telling every how many minute(s) we will get price
    length: 10 # In minutes
    price: 100
  # Enabling this feature will display text in action bar and not in chat
  useActionBar: true
  message:
    rewardMessage: "You got a %item_price% by being active on the server"
  # This isn't recommended due to ability that can lower server's performance
  # Turn on for own risk (No help will be granted until 'stable' version will patch it)
  anti-afk-feature:
    enabled: true

#Don't change this value unless YOU KNOW WHAT YOU ARE DOING
version: 0.51
